import { getAllTournaments } from "@/actions";
import Table from "@/components/Table";

export const metadata = {
  title: "CrossyOff - Schedule",
  description: "Generated by create next app",
};

export const revalidate = 86400

const Schedule = async () => {

  const tournaments = await getAllTournaments()

  return (
    <div id="content" className="column">
      <h1>CrossyOff Tournament Schedule</h1>
      {tournaments.length === 0 ?
        <b style={{ color: "red" }}>Failed to get tournaments</b> :
        <Table rowHeaders={["#", "date", "Name", "Status", "Winner", "Bracket"]} data={tournaments}></Table>
      }
    </div>
  )
}

export default Schedule