import { getAllPlayerElo } from "../../../utility_functions";
import Container from "../../components/shared/Container";
import ContentHeader from "../../components/shared/ContentHeader";
import Button from "../../components/shared/Button";
import Table from "../../components/shared/Table";

export const metadata = {
  title: "CrossyOff - Elo Rankings",
  description: "Generated by create next app",
};

export const revalidate = 1800

const RankingsElo = async () => {

  const players = await getAllPlayerElo()

  return (
    <Container id="content" className="column">
      <ContentHeader text={"CrossyOff Elo Rankings"} />
      { players.length === 0 ?
        <b style={{ color: "red" }}>Failed to get elo rankings</b> :
        <>
          <Button href={"/player_lookup"} style={{ backgroundColor: "red", color: "white" }}>Player Lookup</Button>
          <Table rowHeaders={["#", "Player", "Elo", "Games"]} data={players}></Table>
        </>
      }

    </Container>
  )
}

export default RankingsElo
