import Container from "../components/shared/Container";
import ContentHeader from "../components/shared/ContentHeader";
import PlayerSearch from "../components/custom/PlayerSearch";

export const metadata = {
  title: "CrossyOff - Player Lookup",
  description: "Generated by create next app",
};

const PlayerLookup = () => {
    return (
    <Container id="content" className="column">
      <ContentHeader text={"CrossyOff Player Lookup"}/>
      <PlayerSearch/>
    </Container>
  )
}

export default PlayerLookup