import styles from './page.module.css'
import Image from 'next/image'
import CoverGreeting from './components/home/CoverGreeting';
import CoverDescription from './components/home/CoverDescription';
import Button from './components/shared/Button';
import CoverStats from './components/home/CoverStats';
import Container from './components/shared/Container';

export const metadata = {
  title: "CrossyOff - Home",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <Container className={styles.content}>
      <Image priority={true} sizes='50%, 100%' fill={true} className={styles.cover_img} src="/img/main.png" alt='home logo' />
      <Container className={styles.cover_txt_container}>
        <CoverGreeting color="red" className={styles.cover_greeting} />
        <CoverDescription className={styles.cover_description}/>
        <Button href="https://discord.gg/7Y3rNBT" style={{ left: "100px", top: "50px" }}>
          Join the Community
        </Button>
        <CoverStats containerClass={styles.cover_stats_container} statClass={styles.stat}/>
      </Container>
    </Container>
  );
}
