import { getAllTournaments } from "../../utility_functions";
import Container from "../components/shared/Container";
import ContentHeader from "../components/shared/ContentHeader";
import Table from "../components/shared/Table";

export const metadata = {
  title: "CrossyOff - Schedule",
  description: "Generated by create next app",
};

export const revalidate = 86400

const Schedule = async () => {

  const tournaments = await getAllTournaments()

  return (
    <Container id="content" className="column">
      <ContentHeader text={"CrossyOff Tournament Schedule"} />
      {tournaments.length === 0 ?
        <b style={{ color: "red" }}>Failed to get tournaments</b> :
        <Table rowHeaders={["#", "date", "Name", "Status", "Winner", "Bracket"]} data={tournaments}></Table>
      }
    </Container>
  )
}

export default Schedule
