import SubmitRun from "@/components/SubmitRun"

export const metadata = {
  title: "CrossyOff - Submit Run",
  description: "Generated by create next app",
};

const PlayerLookup = () => {
    return (
    <div id="content" className="column">
      <h1>CrossyOff Submit Run</h1>
      <SubmitRun/>
    </div>
  )
}

export default PlayerLookup