import PlayerSearch from "@/components/PlayerSearch";

export const metadata = {
  title: "CrossyOff - Player Lookup",
  description: "Generated by create next app",
};

const PlayerLookup = () => {
    return (
    <div id="content" className="column">
      <h1>CrossyOff Player Lookup</h1>
      <PlayerSearch/>
    </div>
  )
}

export default PlayerLookup